name: Deploy to GCP VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t mlops-flask-app .

      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_SSH_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            docker stop mlops-flask-app || true
            docker rm mlops-flask-app || true
            docker run -d -p 5000:5000 --name mlops-flask-app mlops-flask-app

