name: Retrain Model

on:
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Retrain model
        run: python src/train_model.py

      - name: Save trained model as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model/model.pkl
