name: Train and Test Model

on:
  push:
    paths:
      - src/**

jobs:
  train-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train Model
        run: |
          python src/train_model.py

      - name: Run Tests
        run: |
          PYTHONPATH=src pytest tests/

